get_kvs:
  name: Get KVS value
  description: Get a value from the device's Key-Value Storage
  fields:
    device_id:
      name: Device
      description: The Shelly device to get the KVS value from
      required: true
      selector:
        device:
          integration: shelly
    key:
      name: Key
      description: The name of the key from which the KVS value will be retrieved
      required: true
      example: "my_key"
      selector:
        text:
